[package]
name = "rust-c-to-armlite"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
bimap = "0.6.3"
codespan-reporting = "0.12.0"
indexmap = "2.13.0"
itertools = "0.14.0"
phf = { version = "0.13.1", features = ["macros"] }
thiserror = "2.0.17"
